/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number;
export function infoTile(z: number, x: number, y: number): string;
export function loadPlanet(path: string, minzoom: number, maxzoom: number): Planet;
export class Planet {
    constructor(path: string, minzoom: number, maxzoom: number);
    tile(z: number, x: number, y: number): Promise<string>;
    static asyncMultiTwo(arg: number): Promise<number>;
}
