/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function loadPlanet(path: string, minzoom: number, maxzoom: number): Planet;
export function pvt(): Promise<void>;
export class Planet {
    constructor(path: string, minzoom: number, maxzoom: number);
    tile(z: number, x: number, y: number): Promise<Uint8Array>;
    static asyncMultiTwo(arg: number): Promise<number>;
}
