[data]
# Source OSM PBF that can be converted
pbf = "./tests/fixtures/santacruz.osm.pbf"
# Working directory where planet data is stored
dir = "./tests/fixtures/santacruz/sort"
# Compressed PVT archive output
pvt = "./tests/fixtures/santacruz.pvt"

# pbf = "/mnt/disks/geodata/osm/planet-2022-11-26.osm.pbf"
# dir = "/mnt/disks/localssd/planet"
# pvt = "/mnt/disks/localssd/planet.pvt"

[render]
leaf_zoom = 12
layer_order = ["Administrative", "Water", "Boundaries", "Buildings", "Landuse", "Major Roads", "Minor Roads"]

[layers]
Administrative = ["admin"]
Water = ["water"]
Boundaries = ["boundaries"]
Buildings = ["buildings"]
Landuse = ["landuse"]
"Major Roads" = ["roads_major"]
"Minor Roads" = ["roads_minor"]

[rules]
admin = { minzoom = 0, values = ["administrative"] }
water = { minzoom = 0, keys = ["water"] }
boundaries = { minzoom = 0, keys = ["boundary"] }
buildings = { minzoom = 10, keys = ["building"] }
landuse = { minzoom = 6, keys = ["landuse"] }
roads_major = { minzoom = 8, values = ["motorway", "trunk", "primary"] }
roads_minor = { minzoom = 12, keys = ["highway"] }
