// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class PVTTilePoint {
    bb: flatbuffers.ByteBuffer | null = null;
    bb_pos = 0;
    __init(i: number, bb: flatbuffers.ByteBuffer): PVTTilePoint {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }

    x(): number {
        return this.bb!.readInt16(this.bb_pos);
    }

    y(): number {
        return this.bb!.readInt16(this.bb_pos + 2);
    }

    static sizeOf(): number {
        return 4;
    }

    static createPVTTilePoint(builder: flatbuffers.Builder, x: number, y: number): flatbuffers.Offset {
        builder.prep(2, 4);
        builder.writeInt16(y);
        builder.writeInt16(x);
        return builder.offset();
    }
}
