[data]
source = "/opt/geodata/daylight/admin-v1.16.osm.pbf"
planet = "/opt/pvt/planets/admin"
archive = "/opt/pvt/archives/admin.pvt"

[render]
leaf_zoom = 12
layer_order = ["Administrative"]
style = "/opt/pvt/styles/basic.json"

[layers]
Administrative = ["admin"]

[rules]
admin = { minzoom = 8, values = ["administrative"] }

# Nodes
# admin_level 3
# place city

# Ways
# boundary administrative
# admin_level 6

# imposm3 example
# https://github.com/omniscale/imposm3/blob/master/example-mapping.yml