[data]
source = "/opt/geodata/daylight/admin-v1.16.osm.pbf"
planet = "/opt/pvt/planets/admin"
archive = "/opt/pvt/archives/admin.pvt"

[render]
leaf_zoom = 12
layer_order = ["Administrative", "Water", "Boundaries", "Buildings", "Landuse", "Major Roads", "Minor Roads"]
style = "/opt/pvt/styles/basic.json"

[layers]
Administrative = ["admin"]
Boundaries = ["boundaries"]

[rules]
# admin_country = { minzoom = 0, tags = [("admin_level", )] }
admin_state = { minzoom = 4, values = ["administrative"] }
admin_county = { minzoom = 4, values = ["administrative"] }
admin_city = { minzoom = 4, values = ["administrative"] }

# Nodes
# admin_level 3
# place city

# Ways
# boundary administrative
# admin_level 6

# imposm3 example
# https://github.com/omniscale/imposm3/blob/master/example-mapping.yml