// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ValueType } from '../planet-vector-tile/value-type';


export class Value {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Value {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

t():ValueType {
  return this.bb!.readUint8(this.bb_pos);
}

v():number {
  return this.bb!.readFloat64(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createValue(builder:flatbuffers.Builder, t: ValueType, v: number):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeFloat64(v);
  builder.pad(7);
  builder.writeInt8(t);
  return builder.offset();
}

}
